# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 592409506600c5e452af3cc558f05492d22deea3a753dfd875ffa9b8a3eda48b1ede8151e84655597325cdd8543e619fcb87aede671362954b19ab47b5e7a381

test:
  secret_key_base: 4d8b1728dedb469c6f614e917a50ff3a04917bce97f568d1468997f2c90936efdcca4f1e5f77b1f534a283ee8d510aad6baafd411aa0fbd435cf5010aa75dc4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
